import { readdirSync, statSync, writeFileSync } from 'fs';
import { basename, extname, join } from 'path';

// Regenerates the front-end catalog modules (src/three/catalog.js and
// src/three/textureList.js) by scanning the committed asset folders under
// public/. Runs automatically via the predev/prebuild npm lifecycle hooks.
//
// Mirrors the original AssetCatalogSeeder rules:
//   - model folder name is the display name; first .glb and first image are used
//   - folders matching floor lamp/pendant/tomon/candle are emissive light sources
//   - PBR texture sets are discovered from <base>_Color.jpg
//   - flat textures are plain image files

const MODELS_SRC = 'public/models';
const PBR_SRC = 'public/textures/pbr-textures';
const FLAT_SRC = 'public/textures/flat-textures';

function capitalizeWords(name) {
  return name
    .split(/\s+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

function slugify(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function collectModels() {
  const catalog = [];
  for (const folder of readdirSync(MODELS_SRC).sort()) {
    const folderPath = join(MODELS_SRC, folder);
    if (!statSync(folderPath).isDirectory()) continue;
    const files = readdirSync(folderPath).sort();
    const model = files.find((file) => file.toLowerCase().endsWith('.glb'));
    const thumbnail = files.find((file) => /\.(png|jpe?g)$/i.test(file));
    if (!model) continue;
    catalog.push({
      id: slugify(folder),
      name: capitalizeWords(folder),
      model: `models/${folder}/${model}`,
      thumbnail: thumbnail ? `models/${folder}/${thumbnail}` : null,
      light: /floor lamp|pendant|tomon|candle/i.test(folder),
    });
  }
  return catalog;
}

function collectTextures() {
  const catalog = [];
  for (const folder of readdirSync(PBR_SRC).sort()) {
    const folderPath = join(PBR_SRC, folder);
    if (!statSync(folderPath).isDirectory()) continue;
    const files = readdirSync(folderPath).sort();
    const color = files.find((file) => /_Color\.jpg$/i.test(file));
    if (!color) continue;
    catalog.push({
      id: slugify(folder),
      name: capitalizeWords(folder),
      file: `textures/pbr-textures/${folder}/${color}`,
    });
  }

  for (const file of readdirSync(FLAT_SRC).sort()) {
    if (!/\.(png|jpe?g)$/i.test(file) || statSync(join(FLAT_SRC, file)).isDirectory()) continue;
    const name = capitalizeWords(basename(file, extname(file)));
    catalog.push({
      id: slugify(name),
      name,
      file: `textures/flat-textures/${file}`,
    });
  }
  return catalog;
}

function formatModelEntry(entry) {
  const thumbnail = entry.thumbnail ? `, thumbnail: '${entry.thumbnail}'` : ', thumbnail: null';
  return `  { id: '${entry.id}', name: '${entry.name}', model: '${entry.model}'${thumbnail}, light: ${entry.light ?? false} },`;
}

function formatTextureEntry(entry) {
  return `  { id: '${entry.id}', name: '${entry.name}', file: '${entry.file}' },`;
}

const catalog = collectModels();
const textures = collectTextures();

const catalogModule = `// GENERATED by scripts/generate-catalog.mjs — do not edit by hand.
// The catalog is discovered from the committed asset folders in public/ and
// regenerated on predev/prebuild, so serves relative URLs that work on
// GitHub Pages (Vite base './').

const base = import.meta.env.BASE_URL;

export function assetUrl(path) {
  return \`\${base}\${path.trim().replace(/^\\/+/, '')}\`;
}

export const modelUrl = assetUrl;
export const textureUrl = assetUrl;

export const catalog = [
${catalog.map(formatModelEntry).join('\n')}
];
`;

const textureModule = `// GENERATED by scripts/generate-catalog.mjs — do not edit by hand.
// The catalog is discovered from the committed asset folders in public/ and
// regenerated on predev/prebuild.

export const textureCatalog = [
${textures.map(formatTextureEntry).join('\n')}
];
`;

writeFileSync('src/three/catalog.js', catalogModule);
writeFileSync('src/three/textureList.js', textureModule);

console.log(`catalog: ${catalog.length} models`);
console.log(`textures: ${textures.length} sets`);